/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountDropdown: typeof import('./client/components/AccountDropdown.vue')['default']
    BackToTop: typeof import('./client/components/BackToTop.vue')['default']
    BonusRulesModal: typeof import('./client/components/Modals/BonusRulesModal.vue')['default']
    BottomNavigation: typeof import('./client/components/BottomNavigation.vue')['default']
    Button: typeof import('./client/components/Button.vue')['default']
    ChangeAvatarModal: typeof import('./client/components/Modals/ChangeAvatarModal.vue')['default']
    ChangeLangSelect: typeof import('./client/components/ChangeLangSelect.vue')['default']
    CircularProgress: typeof import('./client/components/CircularProgress.vue')['default']
    DepositForm: typeof import('./client/components/DepositForm.vue')['default']
    DepositModal: typeof import('./client/components/Modals/DepositModal.vue')['default']
    DepositQRCodeScreen: typeof import('./client/components/DepositQRCodeScreen.vue')['default']
    DepositSuccessScreen: typeof import('./client/components/DepositSuccessScreen.vue')['default']
    ExternalLink: typeof import('./client/components/ExternalLink.vue')['default']
    Footer: typeof import('./client/components/Footer.vue')['default']
    ForgotPasswordModal: typeof import('./client/components/Modals/ForgotPasswordModal.vue')['default']
    GameListItem: typeof import('./client/components/GameListItem.vue')['default']
    GameListSection: typeof import('./client/components/GameListSection.vue')['default']
    Header: typeof import('./client/components/Header.vue')['default']
    HeaderMobile: typeof import('./client/components/HeaderMobile.vue')['default']
    Hero: typeof import('./client/components/Hero.vue')['default']
    HomeLinks: typeof import('./client/components/HomeLinks.vue')['default']
    HomeRecomendations: typeof import('./client/components/HomeRecomendations.vue')['default']
    HomeSkeletonLoading: typeof import('./client/components/HomeSkeletonLoading.vue')['default']
    Input: typeof import('./client/components/Input.vue')['default']
    LevelCard: typeof import('./client/components/LevelCard.vue')['default']
    LoadingScreen: typeof import('./client/components/LoadingScreen.vue')['default']
    LoginModal: typeof import('./client/components/Modals/LoginModal.vue')['default']
    Modal: typeof import('./client/components/Modal.vue')['default']
    Modals: typeof import('./client/components/Modals/Modals.vue')['default']
    ProvidersSection: typeof import('./client/components/ProvidersSection.vue')['default']
    RegisterModal: typeof import('./client/components/Modals/RegisterModal.vue')['default']
    RequiresLogin: typeof import('./client/components/RequiresLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./client/components/SearchBox.vue')['default']
    Sidebar: typeof import('./client/components/Sidebar.vue')['default']
    SidebarLink: typeof import('./client/components/SidebarLink.vue')['default']
    SidebarSection: typeof import('./client/components/SidebarSection.vue')['default']
    Spinner: typeof import('./client/components/Spinner.vue')['default']
    ToastNotification: typeof import('./client/components/ToastNotification.vue')['default']
    TopGames: typeof import('./client/components/TopGames.vue')['default']
    TopMessage: typeof import('./client/components/TopMessage.vue')['default']
    TopWinners: typeof import('./client/components/TopWinners.vue')['default']
    WalletBalanceCard: typeof import('./client/components/WalletBalanceCard.vue')['default']
    WalletDepositsTable: typeof import('./client/components/WalletDepositsTable.vue')['default']
    WalletWithdrawsTable: typeof import('./client/components/WalletWithdrawsTable.vue')['default']
    WithdrawModal: typeof import('./client/components/Modals/WithdrawModal.vue')['default']
    WithdrawRulesModal: typeof import('./client/components/Modals/WithdrawRulesModal.vue')['default']
  }
}
